package main

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"

	// docs is generated by Swag CLI, you have to import it.
	"github.com/morentharia/hacks/xsspobablygo/docs"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
)

type Api struct {
	*gin.Engine
}

func NewApi() Api {
	docs.SwaggerInfo.Title = "Swagger API"
	docs.SwaggerInfo.Description = ""
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = fmt.Sprintf("%s", options.RestAddr)
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	r := Api{gin.Default()}

	r.GET("/swagger/*any", ginSwagger.WrapHandler(
		swaggerFiles.Handler,
		// The url pointing to API definition
		ginSwagger.URL(fmt.Sprintf("http://%s/swagger/doc.json", options.RestAddr)),
	))
	r.GET("/config", r.configHandler)

	return r
}

// Config godoc
// @Accept json
// @Produce json
// @Router /config [get]
// @Success 200 {string} string "answer"
func (a Api) configHandler(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, options)
}
